<a href="https://colab.research.google.com/github/ramvrum/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [4]:
arr = np.random.randint(0, 100, (10, 10))

print(arr)
print("Минимум:", arr.min())
print("Максимум:", arr.max())

[[ 1 97 99 17 12 70 24 82 97  1]
 [44  5 84 60 29 64 91  5 51 77]
 [90 83 18 44 20 42  3 42 41 48]
 [42 58  3 88 52 31 16 48 11 51]
 [46  6 41 25 25 36 26 85 21 15]
 [32 22 82 17 75 11 88 37  7 92]
 [50 69 37  6 27 89 53 11 84 25]
 [17 23 26 36  2 27 29 72 89 46]
 [75  6 59 42 93 81 62 79 12 98]
 [36 31  3 58 43 89 22 50 32 82]]
Минимум: 1
Максимум: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [5]:
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [7]:
z = np.arange(11)

for i in range(len(z)):
    if 3 < z[i] < 8:
        z[i] = -z[i]

print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [8]:
z = np.random.rand(5, 10)
print(z)

for i in range(z.shape[0]):
    avg = z[i].mean()
    z[i] = z[i] - avg

print(z)

[[0.16248508 0.51101071 0.51878814 0.98277683 0.70025166 0.48248624
  0.17761644 0.04906403 0.76143291 0.11319288]
 [0.91317404 0.40425532 0.90545865 0.58080584 0.03955229 0.63023168
  0.4680666  0.61571933 0.26327739 0.53772408]
 [0.65934487 0.69579903 0.97399601 0.25166702 0.88983142 0.12060236
  0.1355507  0.75836501 0.03157768 0.09180397]
 [0.68699425 0.94741125 0.23167161 0.82403917 0.60880937 0.43606309
  0.15012232 0.53022962 0.92639737 0.76941593]
 [0.57071723 0.75904844 0.45133467 0.23835228 0.56283182 0.56202646
  0.52062546 0.90947749 0.18134655 0.31810821]]
[[-0.28342541  0.06510022  0.07287765  0.53686634  0.25434116  0.03657575
  -0.26829405 -0.39684646  0.31552242 -0.33271761]
 [ 0.37734751 -0.1315712   0.36963213  0.04497932 -0.49627423  0.09440516
  -0.06775993  0.07989281 -0.27254913  0.00189755]
 [ 0.19849106  0.23494522  0.5131422  -0.20918679  0.42897761 -0.34025145
  -0.3253031   0.29751121 -0.42927613 -0.36904984]
 [ 0.07587885  0.33629586 -0.37944379  0.21292377

5. Поменяйте 1 и 2 строки матрицы

In [9]:
z = np.arange(25).reshape(5,5)
z[[0, 1]] = z[[1, 0]]

print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [11]:
z = np.random.random((10,2))
x = z[:, 0]
y = z[:, 1]

r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)

polar = np.column_stack((r, theta))

print("Декартовы:\n", z)
print("Полярные (r, theta):\n", polar)

Декартовы:
 [[0.44664987 0.618686  ]
 [0.8046872  0.5732594 ]
 [0.74880871 0.90608224]
 [0.53572823 0.72117839]
 [0.32559026 0.56555653]
 [0.92881102 0.60842286]
 [0.01205191 0.1664445 ]
 [0.32189327 0.68069883]
 [0.10804292 0.07975271]
 [0.83530665 0.57355819]]
Полярные (r, theta):
 [[0.76306518 0.94550136]
 [0.98800194 0.61899992]
 [1.17545714 0.88014918]
 [0.89838911 0.93188617]
 [0.65258196 1.04843698]
 [1.11034602 0.57992104]
 [0.16688026 1.49851452]
 [0.75297156 1.12907385]
 [0.13428986 0.63587886]
 [1.01326511 0.60170576]]


7. Заменить максимальный элемент массива на ноль

In [12]:
z = np.random.random(10)
print(z)

max_index = np.argmax(z)

z[max_index] = 0

print(z)

[0.09544925 0.28594437 0.24389949 0.7418251  0.53015518 0.62195216
 0.62218231 0.9451364  0.50064452 0.93595753]
[0.09544925 0.28594437 0.24389949 0.7418251  0.53015518 0.62195216
 0.62218231 0.         0.50064452 0.93595753]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [13]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print("Индексы", i)
unique_indices = np.unique(i)

z[unique_indices] += 1

print("Итог:", z)

Индексы [6 9 1 9 8 7 4 5 6 7 1 9 2 2 9 8 0 9 4 1]
Итог: [2. 2. 2. 1. 2. 2. 2. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [14]:
z = np.array([1,2,3,4,5])
n_zeros = 3

new_length = len(z) + (len(z) - 1) * n_zeros
arr = np.zeros(new_length, dtype=int)

arr[:: n_zeros + 1] = z

print(arr)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [15]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
index = np.abs(z - v).argmin()

closest = z[index]

print("Число:", v)
print("Ближайшее:", closest)

Число: 90.38564015212744
Ближайшее: 90


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```
Ответ: int64; float64; float128; complex128; float64; int64; bool; <U1; <U21; complex128

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```
Ответ:
1. '41' - строка + строка.
2. -4 - False or -4 → -4.
3. False - and возвращает первый False
4. 1 - True в int64 → 1.
5. Ошибка - нельзя 1j в int64.
6. '1j' - преобразовано в строку.
7. '333' - строку '3' умножили на 3.

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```
Ответ:
1. матрица 3×5, все элементы 1.0
2. матрица 3×5, все элементы 3.14
3. массив [0. , 0.25, 0.5 , 0.75, 1. ]
4. квадратная матрица 3×3 с элементами (1,3,5) на диагонали, остальные 0
5. ошибка
6. матрица 3×3 с случайными числами от 0 до 1
7. единичная матрица 3×3
8. массив из 3 элементов, значения неопределены


**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0] #3
X[-1,-1] #7
X[0:1,-1] #[4]
X[0:2,-1] #[4, 8]
X[0:2,0:2] #[[3, 5], [7, 6]]
X[1,1:3] #[6, 8]
X[1,:] #[7, 6, 8, 8]
X[:,:] #[[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]]
X[:] #[[3, 5, 2, 4], [7, 6, 8, 8], [1, 6, 7, 7]]
X[::2,::2] #[[3, 2], [1, 7]]
X[0:3:2,0:3:2] #[[3, 2], [1, 7]]
X[::-1,::-1] #[[7, 7, 6, 1], [8, 8, 6, 7], [4, 2, 5, 3]]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2]) #делим по строкам
np.split(grid, [2], axis=1) #делим по столбцам
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1] #соединяет списки
    np.array([1, 2, 3]) + np.array([3, 2, 1]) #поэлементное сложение
```

**7**. Как в CodeLab измерить время выполнения кода?

%time — измеряет время выполнения одной строки.

%timeit — выполняет код несколько раз и возвращает среднее время.

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M) #64
np.sum(M, axis=1) #[14, 29, 21]
np.sum(M, axis=0) #[11, 17, 17, 19]
np.sum(M, axis=2) #ошибка
np.sum(M, 1) #[14, 29, 21]
sum(M) #[11, 17, 17, 19]
sum(M,1) #ошибка
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3 #[False, False, False, True]
X < 3 #[True, True, False, False]
X[X < 3] #[1 2]
X[X > 3] #[4]
X[X != 3] #[1 2 4]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?

Преимущество NumPy: быстрее, меньше памяти, удобные векторные операции.

Причина: данные хранятся в одном непрерывном блоке памяти одного типа, что позволяет NumPy выполнять операции на С/Fortran уровне, минуя циклы Python.